### ISSUE TITLE
Milestone 1: Create Homepage

### ISSUE THREAD

**Issue by MonASV** [MonASV/Thats-right-the-game#1]
- [x] Task 1: Setup HTML
- [x] Task 2: Link to js & css files
- [x] Task 3: Populate the board
