### ISSUE TITLE
Milestone 2: successfully  navigate between pages

### ISSUE THREAD

**Issue by MonASV** [MonASV/Thats-right-the-game#2]
- [x] Task 1: Link the html files
- [x] Task 2: Replace content form Index File
- [x] Task 3: Create a page for every category of the game
